### ISSUE TITLE
App Crashes When Loading Songs from File Manager on Android 12

### ISSUE THREAD

**Issue by Basitrajput1511** [ShahzamanRai/Music_player#1]
Your Android app is encountering a critical problem where it crashes consistently upon attempting to load songs from the file manager. This issue is isolated to devices running Android 12. The app functions smoothly on other Android versions, indicating a compatibility problem specifically related to the changes introduced in Android 12.

**Comment by ShahzamanRai** [comment]
Thank you for notifying me about the app crashing issue on Android 12 devices when loading songs from the file manager. I am actively investigating this matter, and I assure you that I am working diligently to address the problem. Please rest assured that I am committed to resolving this issue as soon as possible and appreciate your understanding during this process.

**Comment by ShahzamanRai** [comment]
Thank you for notifying me about the app crashing issue on Android 12 devices when loading songs from the file manager. I am actively investigating this matter, and I assure you that I am working diligently to address the problem. Please rest assured that I am committed to resolving this issue as soon as possible and appreciate your understanding during this process.
